### ISSUE TITLE
Data Type Format validation

### ISSUE THREAD

**Issue by baurchanu** [OpenAPITools/openapi-style-validator#139]
Hi, it might be an option to add validation of [data type format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#data-types).
Use case: 
Date time format validation.
On my current project we use custom formats (not ISO / RFC). So I'd like to have something like this in configuration:

```
<configuration>
    <validateDataTypeFormat>true</validateDataTypeFormat>
    <customDataTypeFormats>
        <customDataTypeFormat>my-date-time</customDataTypeFormat> 
    </customDataTypeFormats>
    <forbiddenDataTypeFormats>
        <forbiddenDataTypeFormat>date-time<forbiddenDataTypeFormat>
    </forbiddenDataTypeFormats>
</configuration>
```
By default all standard OAS formats are allowed and all custom formats are forbidden.

Valid schema:
```
User:
  type: object
  properties:
    birthDateTime:
      type: string
      format: my-date-time
```

Not valid schema:
```
User:
  type: object
  properties:
    birthDateTime:
      type: string
      format: date-time
```
