### ISSUE TITLE
Header definition clashing with naming conventions

### ISSUE THREAD

**Issue by acabarbaye** [OpenAPITools/openapi-style-validator#148]
**Describe the bug**
When describing header parameters which do not follow any naming convention such as `Accept-Version` or `if-none-match`, I get naming convention errors for PATH and Properties

**To Reproduce**
e.g.
```
 parameters:
    acceptVersionParam:
      name: Accept-Version
      in: header
```
results in 
`*ERROR* in path GET /... 'Accept-Version' -> parameter should be in camelCase`
`*ERROR* in path GET / 'Accept-Version' -> parameter should be in camelCase`

**Expected behavior**
No error raised for headers as we have no control over their naming
