### ISSUE TITLE
Validate model properties description

### ISSUE THREAD

**Issue by baurchanu** [OpenAPITools/openapi-style-validator#156]
Hi, I propose to add new validation - validateModelPropertiesDescription, which will ensure that all properties of the Schemas have not empty descriptions.

**Comment by JFCote** [comment]
Hi @baurchanu 
I think this is the idea behind the `isValidateModelNoLocalDef` validation which exist but is currently not implemented. I don't remember why I did not implement it but it was at the very very beginning of the project when it was for my own use.

Why is it called "local" definition? Well, if I remember correctly, it was because you can always have a property who reference to another object/string. Validating this could result in double validation and very nested stuff. It could become complicated very quickly. So the goal was to validate that each property which have a local définition is not null/empty.

I can check again soon why it was more complicated than the other.

**Comment by baurchanu** [comment]
I think we are talking about two different validations:) My proposal is quite simple.

Example:
Success:
```
User:
  type: object
  properties:
    name:
      type: string
      description: First name and last name
```

Fail:
```
User:
  type: object
  properties:
    name:
      type: string
```
---------------------------------------------------------------------------------------
> Validating this could result in double validation and very nested stuff.

It can be a solution:
1) Skip refs to other files 
2) Skip refs to other objects, because they will be validated separately
3) One time validation of refs to other data types
