### ISSUE TITLE
Validate model required properties

### ISSUE THREAD

**Issue by baurchanu** [OpenAPITools/openapi-style-validator#157]
Hi, I propose to add new validation - validateModelRequiredProperties, which will ensure that all required properties of the Schemas are existing.

Success:
```
User:
  type: object
  required:
    - name
  properties:
    name:
      type: string
```

Fail:
```
User:
  type: object
  required:
    - id
  properties:
    name:
      type: string
```
