### ISSUE TITLE
Update Github action with setup-java to use cache

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-style-validator#245]
Need to add this:

```
steps:
- uses: actions/checkout@v2
- uses: actions/setup-java@v2
  with:
    distribution: 'temurin'
    java-version: '11'
    cache: 'gradle'
- run: ./gradlew build
```
