### ISSUE TITLE
'_links' -> property should be in camelCase

### ISSUE THREAD

**Issue by gervaisb** [OpenAPITools/openapi-style-validator#582]
**Describe the bug**
We have an OpenAPI specification that describe some resources with the HAL format. Those resources have a `_links` property that is rejected by the camelCase format.

**To Reproduce**
```
    SomeHalResource:
      type: object
      required:
        - _links
      properties:
        _links:
          type: object
          required:
            - self
          properties:
            self:
              type: string
```

**Expected behavior**

`_links` should be accepted as camelCase or we should have another format that accept camelCase and hyphen.
